### ISSUE TITLE
Cookietology 1.18.2 Update?

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [EterDelta/Cookietology#2]
I REALLY like the idea of this mod, and would **love** to use it, but I'm currently playing on 1.18.2 (until my current mods update to 1.19), and your Cookietology mod unfortunately doesn't work on 1.18.2.  Any chance that you could update it, either to 1.18.2, or else (better yet?) to 1.19?!?  Please and thank you!!!

**Comment by EterDelta** [comment]
Sadly, this version of Cookietology has been abandoned.
You probably want to check out **Cookietology: Rebaked**, which is a rewrite of Cookietology for the 1.19, available on both Forge and Fabric.

https://www.curseforge.com/minecraft/mc-mods/cookietology-rebaked
